languageCode = "es"
languageName = "Espa침ol"
weight = 1
title = "El Diario Del Codorniz"

[params]
  displayName = "Espa침ol"
  isoCode = "es"
  rtl = false
  dateFormat = "02/01/2006"
  logo = "img/blowfish_logo_transparent.png"
  description = ""
copyright = ""

[params.author]
  name = "Ronny Gonz치lez"
  email = "yordemblo@gmail.com"
  # image = "img/author2.png"
  headline = "Desarrollador Web"
  bio = "Interesado en aprender y en los retos tecnol칩gicos"
  links = [
         { linkedin = "https://www.linkedin.com/in/ronny-omnier-gonz%C3%A1lez-vargas-a12480186/" },
    { x-twitter = "https://twitter.com/ronnyg2121" },
    { github = "https://github.com/ronnyg2121" },
  ]